import json
import csv
import os

# --- TEMPLATES ---
JS_TEMPLATE = """// @ts-check
// MASTER SCRIPT - OPTIMIZED
// This file was automatically generated by the Unified Artifact Tool.
/**
 * --- SCRIPT DOCUMENTATION ---
 * This is a master script that consolidates all artifact locking logic into a single,
 * intelligent filter.
 */
/**
 * @typedef {{key: string}} Substat
 * @typedef {{
 *  setKey: string;
 *  slotKey: 'flower' | 'plume' | 'sands' | 'circlet' | 'goblet';
 *  mainStatKey: string;
 *  rarity: number;
 *  level: number;
 *  substats: Substat[];
 * }} Artifact
 */

// --- CONFIGURATION ---
const CONFIG = {
  DESIRED_SUBSTAT_COUNT_4_LINE: 3,
  DESIRED_SUBSTAT_COUNT_3_LINE: 2,
};

// --- DATA: GENERATED FROM CSV ---
const FLOWER_PLUME_BUILDS = {FLOWER_PLUME_BUILDS_JSON};
const GSC_RAW_BUILDS = {GSC_RAW_BUILDS_JSON};

// --- PERFORMANCE INDEXING ---
const OPTIMIZED_GSC_INDEX = { sands: {}, goblet: {}, circlet: {} };

function addToIndex(slot, mainStats, desiredSubs) {
  if (!mainStats) return;
  const desiredSet = new Set(desiredSubs);
  mainStats.forEach(mainStat => {
    if (!OPTIMIZED_GSC_INDEX[slot][mainStat]) OPTIMIZED_GSC_INDEX[slot][mainStat] = [];
    OPTIMIZED_GSC_INDEX[slot][mainStat].push(desiredSet);
  });
}

if (Array.isArray(GSC_RAW_BUILDS)) {
  GSC_RAW_BUILDS.forEach(build => {
    addToIndex('sands', build.sands_main, build.substats_desired);
    addToIndex('goblet', build.goblet_main, build.substats_desired);
    addToIndex('circlet', build.circlet_main, build.substats_desired);
  });
}

// --- MAIN LOGIC ---
module.exports = (artifact) => {
  if (artifact.rarity < 5) return false;
  const artifactSubstats = artifact.substats.map(s => s.key);

  let hasCR = false, hasCD = false;
  for (const key of artifactSubstats) {
    if (key === 'critRate_') hasCR = true;
    if (key === 'critDMG_') hasCD = true;
  }
  if (hasCR && hasCD) return true;

  const threshold = artifact.substats.length === 4 ? CONFIG.DESIRED_SUBSTAT_COUNT_4_LINE : CONFIG.DESIRED_SUBSTAT_COUNT_3_LINE;
  const { slotKey, setKey, mainStatKey } = artifact;

  if (slotKey === 'flower' || slotKey === 'plume') {
    const buildsForSet = FLOWER_PLUME_BUILDS[setKey];
    if (!buildsForSet) return false;
    for (const build of buildsForSet) {
      let matchCount = 0;
      for (const sub of artifactSubstats) {
        if (build.substats_desired.includes(sub)) matchCount++;
      }
      if (matchCount >= threshold) return true;
    }
    return false;
  }
  
  const validBuilds = OPTIMIZED_GSC_INDEX[slotKey]?.[mainStatKey];
  if (!validBuilds) return false;

  for (const desiredSet of validBuilds) {
    let matchCount = 0;
    for (const sub of artifactSubstats) {
      if (desiredSet.has(sub)) matchCount++;
    }
    if (matchCount >= threshold) return true;
  }
  return false;
};
"""

# --- HELPER FUNCTIONS ---
def parse_list(text):
    """Parses a comma-separated string from the CSV into a clean sorted list."""
    if not text: return []
    return sorted([x.strip() for x in text.split(',') if x.strip()])
    
def generate_js_from_csv(csv_path, js_path):
    """Generates the JS filter file from the exact keys in the CSV."""
    fp_grouped = {} 
    gsc_grouped = {}

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            char_name = row.get('Character Name', 'Unknown')
            raw_sets = parse_list(row.get('Top Artifact Sets', ''))
            
            sands_stats = parse_list(row.get('Common Sands', ''))
            goblet_stats = parse_list(row.get('Common Goblet', ''))
            circlet_stats = parse_list(row.get('Common Circlet', ''))
            substats = parse_list(row.get('Substat Priority', ''))

            if not substats: continue

            # --- Process for FLOWER_PLUME_BUILDS ---
            for app_key in raw_sets:
                if app_key not in fp_grouped:
                    fp_grouped[app_key] = {}
                
                sub_tuple = tuple(substats)
                if sub_tuple not in fp_grouped[app_key]:
                    fp_grouped[app_key][sub_tuple] = { "substats": substats, "chars": set() }
                fp_grouped[app_key][sub_tuple]["chars"].add(char_name)

            # --- Process for GSC_RAW_BUILDS ---
            build_key = (tuple(sands_stats), tuple(goblet_stats), tuple(circlet_stats), tuple(substats))
            if build_key not in gsc_grouped:
                gsc_grouped[build_key] = {
                    "data": {
                        "sands_main": sands_stats,
                        "goblet_main": goblet_stats,
                        "circlet_main": circlet_stats,
                        "substats_desired": substats
                    },
                    "chars": set()
                }
            gsc_grouped[build_key]["chars"].add(char_name)

    # --- Final Transformation ---
    final_fp_builds = {}
    for set_key, builds_map in fp_grouped.items():
        final_fp_builds[set_key] = []
        for build_obj in builds_map.values():
            final_fp_builds[set_key].append({
                "substats_desired": build_obj["substats"],
                "source_characters": sorted(list(build_obj["chars"]))
            })
    
    final_gsc_builds = []
    for build_obj in gsc_grouped.values():
        entry = build_obj["data"]
        entry["source_characters"] = sorted(list(build_obj["chars"]))
        final_gsc_builds.append(entry)
    
    fp_json = json.dumps(final_fp_builds, indent=2)
    gsc_json = json.dumps(final_gsc_builds, indent=2)
    
    output_content = JS_TEMPLATE.replace('{FLOWER_PLUME_BUILDS_JSON}', fp_json)
    output_content = output_content.replace('{GSC_RAW_BUILDS_JSON}', gsc_json)

    with open(js_path, 'w', encoding='utf-8') as f:
        f.write(output_content)
        
    return len(final_fp_builds), len(final_gsc_builds)