import re
import json
import csv
import os

# --- TEMPLATES ---

JS_TEMPLATE = """// @ts-check
// MASTER SCRIPT - OPTIMIZED
// This file was automatically generated by the Unified Artifact Tool.
/**
 * --- SCRIPT DOCUMENTATION ---
 * This is a master script that consolidates all artifact locking logic into a single,
 * intelligent filter.
 * 
 * STRATEGY:
 * 1. Flower/Plumes: Checked against specific Sets defined in `FLOWER_PLUME_BUILDS`.
 * 2. Sands/Goblet/Circlet: Checked against a high-performance Index built from `GSC_RAW_BUILDS`.
 *    - This allows for "Scarcity Management" (keeping rare off-pieces) without performance cost.
 */
/**
 * @typedef {{key: string}} Substat
 * @typedef {{
 *  setKey: string;
 *  slotKey: 'flower' | 'plume' | 'sands' | 'circlet' | 'goblet';
 *  mainStatKey: string;
 *  rarity: number;
 *  level: number;
 *  substats: Substat[];
 * }} Artifact
 */

// --- CONFIGURATION ---
const CONFIG = {
  // For a Level 0 artifact that starts with 4 substats, require this many desirable substats to lock.
  DESIRED_SUBSTAT_COUNT_4_LINE: 3,
  // For a Level 0 artifact that starts with 3 substats, require this many desirable substats to lock.
  DESIRED_SUBSTAT_COUNT_3_LINE: 2,
};

// --- DATA: GENERATED FROM CSV ---

// Builds specifically for Flowers and Plumes, where only substats matter.
const FLOWER_PLUME_BUILDS = {FLOWER_PLUME_BUILDS_JSON};

// A raw list of general-purpose builds for Sands, Goblets, and Circlets.
// Each entry defines a valid combination of main stats and desired substats.
const GSC_RAW_BUILDS = {GSC_RAW_BUILDS_JSON};

// --- PERFORMANCE INDEXING (RUNTIME OPTIMIZATION) ---
// This runs once when the script is loaded.
// It converts the linear GSC_RAW_BUILDS list into a hash map for O(1) lookups.

const OPTIMIZED_GSC_INDEX = {
  sands: {},
  goblet: {},
  circlet: {}
};

// Helper to populate the index
function addToIndex(slot, mainStats, desiredSubs) {
  if (!mainStats) return;
  // Convert desired subs to a Set for O(1) lookup speed during scanning
  const desiredSet = new Set(desiredSubs);
  
  mainStats.forEach(mainStat => {
    if (!OPTIMIZED_GSC_INDEX[slot][mainStat]) {
      OPTIMIZED_GSC_INDEX[slot][mainStat] = [];
    }
    OPTIMIZED_GSC_INDEX[slot][mainStat].push(desiredSet);
  });
}

// Build the Index immediately
if (Array.isArray(GSC_RAW_BUILDS)) {
  GSC_RAW_BUILDS.forEach(build => {
    addToIndex('sands', build.sands_main, build.substats_desired);
    addToIndex('goblet', build.goblet_main, build.substats_desired);
    addToIndex('circlet', build.circlet_main, build.substats_desired);
  });
}

// --- MAIN LOGIC ---

/**
 * Main function to determine if an artifact should be locked.
 * @param {Artifact} artifact - The artifact to evaluate.
 * @returns {boolean | null} - True to lock, false to unlock, null to ignore.
 */
module.exports = (artifact) => {
  
  // Rule 0: Ignore anything that isn't a 5-star artifact.
  if (artifact.rarity < 5) return false;

  const artifactSubstats = artifact.substats.map(s => s.key);

  // Rule 1: Universal lock for any piece with both Crit Rate and Crit Damage.
  // This is a safety net for high-potential pieces regardless of set.
  let hasCR = false;
  let hasCD = false;
  for (const key of artifactSubstats) {
    if (key === 'critRate_') hasCR = true;
    if (key === 'critDMG_') hasCD = true;
  }
  if (hasCR && hasCD) return true;

  // Determine the minimum number of desired substats required based on starting lines.
  const threshold = artifact.substats.length === 4
    ? CONFIG.DESIRED_SUBSTAT_COUNT_4_LINE
    : CONFIG.DESIRED_SUBSTAT_COUNT_3_LINE;

  const { slotKey, setKey, mainStatKey } = artifact;

  // Rule 2a: Logic for Flowers and Plumes (Strict Set Matching).
  if (slotKey === 'flower' || slotKey === 'plume') {
    const buildsForSet = FLOWER_PLUME_BUILDS[setKey];
    if (!buildsForSet) return false; // This set is not in our desired list for F/P.

    // Check if the artifact's substats match any of the defined builds for this set.
    for (const build of buildsForSet) {
      let matchCount = 0;
      for (const sub of artifactSubstats) {
        if (build.substats_desired.includes(sub)) matchCount++;
      }
      if (matchCount >= threshold) return true;
    }
    return false;
  }
  
  // Rule 2b: Logic for Sands, Goblets, and Circlets (Indexed Lookup).
  // We check the optimized index to see if ANY build needs this Main Stat + Slot combo.
  
  const validBuilds = OPTIMIZED_GSC_INDEX[slotKey]?.[mainStatKey];
  
  // If NO character in the database uses this Main Stat on this Slot, trash it.
  if (!validBuilds) return false;

  // Check against the specific builds that use this Main Stat
  for (const desiredSet of validBuilds) {
    let matchCount = 0;
    for (const sub of artifactSubstats) {
      // Set.has() is instant (O(1)) compared to Array.includes()
      if (desiredSet.has(sub)) matchCount++;
    }
    if (matchCount >= threshold) return true;
  }

  // If no rules were met, do not lock the artifact.
  return false;
};
"""

# --- HELPER FUNCTIONS ---

def camel_to_words(name):
    """Converts a CamelCase string like 'ArchaicPetra' to 'Archaic Petra'."""
    return re.sub(r'(?<!^)(?=[A-Z])', ' ', name)

def parse_sets_enum(file_path):
    """
    Parses sets_enum.ts to create a mapping from Human Name -> Script Key.
    Also generates a reverse mapping for normalization (lowercase -> Script Key).
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"'{file_path}' not found.")

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Matches lines like: ArchaicPetra = 'ArchaicPetra',
    pattern = re.compile(r"\s*(\w+)\s*=\s*'.*?',")
    matches = pattern.findall(content)
    
    human_to_key = {}
    normalization_map = {}
    
    for key in matches:
        human_name = camel_to_words(key)
        human_to_key[human_name] = key
        
        # Create normalization entries
        normalization_map[key.lower()] = key
        normalization_map[human_name.lower()] = key
        normalization_map[human_name.replace(" ", "").lower()] = key
        
    return human_to_key, normalization_map

def normalize_key(text, normalization_map):
    """Normalizes a string to the script key using the map."""
    if not text: return ""
    clean_text = re.sub(r'[^a-z0-9]', '', text.lower())
    return normalization_map.get(clean_text)

def clean_csv_value(text):
    """Removes (xx%) from CSV values."""
    if not text: return ""
    text = re.sub(r'\s*\(.*?\)', '', text)
    return text.strip()

def parse_list(text):
    """Parses a comma-separated string from the CSV into a clean list."""
    if not text: return []
    # Uses clean_csv_value to ensure matching logic works even with verbose CSVs
    return sorted([clean_csv_value(x) for x in text.split(',') if x.strip()])
    
def generate_js_from_csv(csv_path, js_path, sets_enum_path):
    """
    Generates the JS filter file from the CSV. 
    Now includes 'source_characters' in the output for debugging/sanity checking.
    """
    _, normalization_map = parse_sets_enum(sets_enum_path)
    
    # Dictionary structure: 
    # { SetKey: { SubstatsTuple: { "substats": [], "chars": set() } } }
    fp_grouped = {} 
    
    # Dictionary structure:
    # { BuildTuple: { "data": dict, "chars": set() } }
    gsc_grouped = {}

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            char_name = row.get('Character Name', 'Unknown')
            raw_sets = parse_list(row.get('Top Artifact Sets', ''))
            
            sands_stats = parse_list(row.get('Common Sands', ''))
            goblet_stats = parse_list(row.get('Common Goblet', ''))
            circlet_stats = parse_list(row.get('Common Circlet', ''))
            substats = parse_list(row.get('Substat Priority', ''))

            if not substats: continue

            # --- Process for FLOWER_PLUME_BUILDS ---
            for raw_set in raw_sets:
                app_key = normalize_key(raw_set, normalization_map)
                if not app_key: continue

                if app_key not in fp_grouped:
                    fp_grouped[app_key] = {}
                
                sub_tuple = tuple(substats)
                if sub_tuple not in fp_grouped[app_key]:
                    fp_grouped[app_key][sub_tuple] = { "substats": substats, "chars": set() }
                
                fp_grouped[app_key][sub_tuple]["chars"].add(char_name)

            # --- Process for GSC_RAW_BUILDS ---
            # Create a unique key for this specific build configuration
            build_key = (tuple(sands_stats), tuple(goblet_stats), tuple(circlet_stats), tuple(substats))
            
            if build_key not in gsc_grouped:
                gsc_grouped[build_key] = {
                    "data": {
                        "sands_main": sands_stats,
                        "goblet_main": goblet_stats,
                        "circlet_main": circlet_stats,
                        "substats_desired": substats
                    },
                    "chars": set()
                }
            gsc_grouped[build_key]["chars"].add(char_name)

    # --- Final Transformation to List/JSON format ---
    
    # 1. Transform Flower/Plume
    final_fp_builds = {}
    for set_key, builds_map in fp_grouped.items():
        final_fp_builds[set_key] = []
        for build_obj in builds_map.values():
            final_fp_builds[set_key].append({
                "substats_desired": build_obj["substats"],
                "source_characters": sorted(list(build_obj["chars"])) # The "Comment"
            })
    
    # 2. Transform GSC
    final_gsc_builds = []
    for build_obj in gsc_grouped.values():
        entry = build_obj["data"]
        entry["source_characters"] = sorted(list(build_obj["chars"])) # The "Comment"
        final_gsc_builds.append(entry)
    
    fp_json = json.dumps(final_fp_builds, indent=2)
    gsc_json = json.dumps(final_gsc_builds, indent=2)
    
    output_content = JS_TEMPLATE.replace('{FLOWER_PLUME_BUILDS_JSON}', fp_json)
    output_content = output_content.replace('{GSC_RAW_BUILDS_JSON}', gsc_json)

    with open(js_path, 'w', encoding='utf-8') as f:
        f.write(output_content)
        
    return len(final_fp_builds), len(final_gsc_builds)