// @ts-check
// MASTER SCRIPT - OPTIMIZED
// This file was automatically generated by the Unified Artifact Tool.
/**
 * --- SCRIPT DOCUMENTATION ---
 * This is a master script that consolidates all artifact locking logic into a single,
 * intelligent filter.
 * 
 * STRATEGY:
 * 1. Flower/Plumes: Checked against specific Sets defined in `FLOWER_PLUME_BUILDS`.
 * 2. Sands/Goblet/Circlet: Checked against a high-performance Index built from `GSC_RAW_BUILDS`.
 *    - This allows for "Scarcity Management" (keeping rare off-pieces) without performance cost.
 */
/**
 * @typedef {{key: string}} Substat
 * @typedef {{
 *  setKey: string;
 *  slotKey: 'flower' | 'plume' | 'sands' | 'circlet' | 'goblet';
 *  mainStatKey: string;
 *  rarity: number;
 *  level: number;
 *  substats: Substat[];
 * }} Artifact
 */

// --- CONFIGURATION ---
const CONFIG = {
  // For a Level 0 artifact that starts with 4 substats, require this many desirable substats to lock.
  DESIRED_SUBSTAT_COUNT_4_LINE: 3,
  // For a Level 0 artifact that starts with 3 substats, require this many desirable substats to lock.
  DESIRED_SUBSTAT_COUNT_3_LINE: 2,
};

// --- DATA: GENERATED FROM CSV ---

// Builds specifically for Flowers and Plumes, where only substats matter.
const FLOWER_PLUME_BUILDS = {
  "Instructor": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Amber_BUFF SUPPORT",
        "Sucrose_EM SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kirara_SHIELD SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Gorou_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Aino_REACTION SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "MC (Hydro)_SUPPORT",
        "Mona_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Bennett_SUPPORT"
      ]
    }
  ],
  "ViridescentVenerer": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Heizou_ANEMO DPS",
        "Ifa_ANEMO DPS",
        "Ifa_REACTION DPS",
        "Jean_HEAL SUPPORT & DAMAGE",
        "MC (Anemo)_ANEMO DPS",
        "Sucrose_EM SUPPORT",
        "Venti_OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Heizou_REACTION DPS",
        "Jahoda_OFF-FIELD REACTION DPS & HEAL SUPPORT",
        "Jean_REACTION DPS",
        "Lanyan_DRIVER",
        "Lanyan_SHIELD & BUFFSUPPORT",
        "Sayu_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Lynette_OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Mizuki_REACTION DPS"
      ]
    }
  ],
  "NoblesseOblige": [
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Heizou_REACTION DPS",
        "Sayu_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Charlotte_HEAL SUPPORT",
        "Durin_BUFF SUPPORT & OFF-FIELD DPS",
        "Faruzan_BUFF SUPPORT",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Iansan_BUFF SUPPORT",
        "MC (Electro)_ENERGY SUPPORT",
        "Mona_BUFF SUPPORT",
        "Rosaria_BUFF SUPPORT",
        "Sara_BUFF SUPPORT & DAMAGE",
        "Xingqiu_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Xingqiu_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Aloy_BURST SUPPORT",
        "Amber_BUFF SUPPORT",
        "Beidou_OFF-FIELD DPS",
        "Chongyun_BURST NUKE",
        "Chongyun_INFUSION SUPPORT",
        "Collei_REACTION SUPPORT",
        "Jean_HEAL SUPPORT & DAMAGE",
        "Kaeya_REVERSE MELT",
        "MC (Anemo)_ANEMO DPS",
        "MC (Dendro)_REACTION SUPPORT",
        "Mona_BURST NUKE(OUT OF DATE)",
        "Ororon_OFF-FIELD DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Dahlia_SHIELD SUPPORT",
        "Diona_HEAL & SHIELD SUPPORT",
        "Mika_HEAL & BUFF SUPPORT",
        "Thoma_SHIELD SUPPORT",
        "Yelan_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Yelan_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Chevreuse_BUFF SUPPORT",
        "Dori_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Gorou_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Aino_REACTION SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Bennett_SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Chevreuse_BUFF SUPPORT & DAMAGE"
      ]
    }
  ],
  "GoldenTroupe": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Fischl_OFF-FIELD AGGRAVATE DPS",
        "Fischl_OFF-FIELD DPS",
        "Freminet_CRYO DPS",
        "Heizou_ANEMO DPS",
        "Yaemiko_OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Escoffier_HIGH ENERGY REQUIREMENT (OFF-FIELD DPS)",
        "Escoffier_LOW ENERGY REQUIREMENT (OFF-FIELD DPS)",
        "MC (Geo)_GEO DPS",
        "Navia_DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Chiori_OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Furina_OFF-FIELD DPS & BUFF SUPPORT"
      ]
    }
  ],
  "ScrollOfTheHeroOfCinderCity": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Faruzan_BUFF SUPPORT",
        "Iansan_BUFF SUPPORT",
        "MC (Electro)_ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Barbara_HEAL SUPPORT",
        "Candace_BUFF SUPPORT",
        "Dahlia_SHIELD SUPPORT",
        "Dehya_SUPPORT",
        "Diona_HEAL & SHIELD SUPPORT",
        "Layla_SHIELD SUPPORT",
        "Zhongli_SHIELD SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Qiqi_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Aino_REACTION SUPPORT",
        "Citlali_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Lisa_OFF-FIELD DPS & SUPPORT",
        "Ororon_OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Kachina_BUFF & REACTION SUPPORT",
        "Xilonen_BUFF & HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Chevreuse_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "MC (Pyro)_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Mavuika_DPS & BUFF SUPPORT"
      ]
    }
  ],
  "EmblemOfSeveredFate": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Kaeya_FREEZE / MONO CRYO",
        "Lynette_OFF-FIELD DPS",
        "Ningguang_DPS",
        "Rosaria_FREEZE",
        "Sara_BUFF SUPPORT & DAMAGE",
        "Xingqiu_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Xingqiu_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD AGGRAVATE DPS",
        "Beidou_OFF-FIELD DPS",
        "Chongyun_BURST NUKE",
        "Freminet_PHYSICAL DPS",
        "Kaeya_REVERSE MELT",
        "Lisa_OFF-FIELD DPS & SUPPORT",
        "Mona_BURST NUKE(OUT OF DATE)",
        "Raiden_DPS & ENERGY SUPPORT",
        "Rosaria_REVERSEMELT",
        "Xiangling_OFF-FIELD DPS",
        "Xiangling_OFF-FIELD VAPORIZE DPS",
        "Yaemiko_OFF-FIELD AGGRAVATE DPS",
        "Yaemiko_OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Yunjin_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Zhongli_BURST SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Candace_BUFF SUPPORT",
        "Yanfei_SHIELD SUPPORT [C4+ REQUIRED]",
        "Yelan_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Yelan_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Xinyan_PHYSICAL DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Dehya_ON FIELD DPS"
      ]
    }
  ],
  "ObsidianCodex": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Ifa_ANEMO DPS",
        "MC (Pyro)_DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Mualani_VAPORIZE DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Mavuika_DPS & BUFF SUPPORT"
      ]
    }
  ],
  "DeepwoodMemories": [
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Jahoda_OFF-FIELD REACTION DPS & HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Collei_REACTION SUPPORT",
        "MC (Dendro)_REACTION SUPPORT",
        "Nahida_BUFF SUPPORT & DAMAGE",
        "Xiangling_OFF-FIELD DPS",
        "Xiangling_OFF-FIELD VAPORIZE DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kirara_SHIELD SUPPORT",
        "Yaoyao_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Aino_REACTION SUPPORT",
        "Kaveh_BLOOM / BURGEON DRIVER",
        "Lauma_BUFF SUPPORT (HIGH-ENERGY REQUIREMENT)",
        "Lauma_BUFF SUPPORT(LOW-ENERGY REQUIREMENT)"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Emilie_OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Dori_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Mavuika_DPS & BUFF SUPPORT"
      ]
    }
  ],
  "SilkenMoonsSerenade": [
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Jahoda_OFF-FIELD REACTION DPS & HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Aino_REACTION SUPPORT",
        "Lauma_BUFF SUPPORT (HIGH-ENERGY REQUIREMENT)",
        "Lauma_BUFF SUPPORT(LOW-ENERGY REQUIREMENT)"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Gorou_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Columbina_OFF-FIELD DPS & BUFF SUPPORT"
      ]
    }
  ],
  "ADayCarvedFromRisingWinds": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Durin_VAPORIZE / MELT OFF-FIELD DPS",
        "Fischl_OFF-FIELD AGGRAVATE DPS",
        "Fischl_OFF-FIELD DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT",
        "Venti_OFF-FIELD DPS",
        "Venti_ON-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Durin_BUFF SUPPORT & OFF-FIELD DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Ningguang_DPS",
        "Razor_DPS"
      ]
    }
  ],
  "AubadeOfMorningstarAndMoon": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Kaeya_REVERSE MELT",
        "MC (Anemo)_ANEMO DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Nilou_BLOOM SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Columbina_OFF-FIELD DPS & BUFF SUPPORT"
      ]
    }
  ],
  "DesertPavilionChronicle": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "MC (Anemo)_ANEMO DPS",
        "Sethos_NORMAL ATTACK DPS",
        "Venti_ON-FIELD DPS"
      ]
    }
  ],
  "EchoesOfAnOffering": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Ningguang_DPS",
        "Razor_DPS"
      ]
    }
  ],
  "FlowerOfParadiseLost": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Kaeya_REVERSE MELT",
        "Lisa_REACTION DPS",
        "MC (Anemo)_ANEMO DPS"
      ]
    },
    {
      "substats_desired": [
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kokomi_BLOOM DPS",
        "Kuki_HYPERBLOOM",
        "Thoma_BURGEON"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Barbara_BLOOM DPS",
        "Raiden_HYPERBLOOM"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Nilou_BLOOM SUPPORT"
      ]
    }
  ],
  "FragmentOfHarmonicWhimsy": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Clorinde_DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Ningguang_DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Arlecchino_DPS"
      ]
    }
  ],
  "GildedDreams": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Diluc_DPS",
        "Durin_VAPORIZE / MELT OFF-FIELD DPS",
        "Kaeya_REVERSE MELT",
        "Keqing_QUICKBLOOM DPS",
        "Lisa_AGGRAVATE DPS",
        "MC (Anemo)_ANEMO DPS",
        "Nahida_BUFF SUPPORT & DAMAGE",
        "Rosaria_REVERSEMELT",
        "Sethos_CHARGED ATTACK DPS",
        "Tighnari_QUICK SWAP DPS",
        "Yaemiko_OFF-FIELD AGGRAVATE DPS",
        "Yanfei_VAPORIZE DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Razor_HYPERBLOOM / REACTION DPS"
      ]
    },
    {
      "substats_desired": [
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kuki_HYPERBLOOM",
        "Thoma_BURGEON"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kuki_AGGRAVATE OFF-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Dehya_REACTION DPS",
        "Nilou_BLOOM SUPPORT"
      ]
    }
  ],
  "GladiatorsFinale": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Clorinde_DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Ningguang_DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Arlecchino_DPS"
      ]
    }
  ],
  "NightOfTheSkysUnveiling": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Kaeya_REVERSE MELT",
        "MC (Anemo)_ANEMO DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Nefer_DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Nilou_BLOOM SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Columbina_OFF-FIELD DPS & BUFF SUPPORT"
      ]
    }
  ],
  "NighttimeWhispersInTheEchoingWoods": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "MC (Geo)_GEO DPS",
        "Navia_DPS",
        "Ningguang_DPS"
      ]
    }
  ],
  "ShimenawasReminiscence": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Amber_MELT DPS",
        "Ganyu_MELT DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Ningguang_DPS"
      ]
    }
  ],
  "UnfinishedReverie": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Ganyu_MELT DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Emilie_OFF-FIELD DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Ningguang_DPS"
      ]
    }
  ],
  "VermillionHereafter": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Freminet_CRYO DPS",
        "MC (Anemo)_ANEMO DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Ningguang_DPS"
      ]
    }
  ],
  "WanderersTroupe": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Kaeya_REVERSE MELT",
        "MC (Anemo)_ANEMO DPS",
        "Sethos_CHARGED ATTACK DPS",
        "Sethos_NORMAL ATTACK DPS",
        "Tighnari_QUICK SWAP DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Ganyu_MELT DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Nilou_BLOOM SUPPORT"
      ]
    }
  ],
  "BlizzardStrayer": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ayaka_DPS",
        "Escoffier_HIGH ENERGY REQUIREMENT (OFF-FIELD DPS)",
        "Escoffier_LOW ENERGY REQUIREMENT (OFF-FIELD DPS)",
        "Ganyu_FREEZE DPS",
        "Ganyu_MONO CRYO DPS",
        "Kaeya_FREEZE / MONO CRYO",
        "Rosaria_FREEZE",
        "Xingqiu_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Xingqiu_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Aloy_BURST SUPPORT",
        "Freminet_CRYO DPS",
        "Kaeya_REVERSE MELT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Layla_SHIELD SUPPORT AND DAMAGE"
      ]
    }
  ],
  "FinaleOfTheDeepGalleries": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Kaeya_REVERSE MELT"
      ]
    }
  ],
  "TenacityOfTheMillelith": [
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Dehya_SUPPORT",
        "Furina_OFF-FIELD DPS & BUFF SUPPORT",
        "Layla_SHIELD SUPPORT",
        "Yanfei_SHIELD SUPPORT [C4+ REQUIRED]",
        "Yaoyao_HEAL SUPPORT",
        "Yelan_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Yelan_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Layla_SHIELD SUPPORT AND DAMAGE"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Charlotte_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Qiqi_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Citlali_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Kuki_HEAL SUPPORT",
        "Nilou_BLOOM SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kokomi_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "MC (Pyro)_BUFF SUPPORT",
        "Xinyan_SHIELD SUPPORT"
      ]
    }
  ],
  "OceanHuedClam": [
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Barbara_HEAL SUPPORT",
        "Mika_HEAL & BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Kaveh_BLOOM / BURGEON DRIVER"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kokomi_HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "eleMas",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Kokomi_DPS"
      ]
    }
  ],
  "MarechausseeHunter": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Diluc_DPS",
        "Freminet_CRYO DPS",
        "Freminet_PHYSICAL DPS",
        "Gaming_DPS",
        "Yanfei_VAPORIZE DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Lyney_DPS",
        "Razor_DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Noelle_DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "MC (Hydro)_ON-FIELD DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Mualani_VAPORIZE DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas"
      ],
      "source_characters": [
        "Mavuika_DPS & BUFF SUPPORT"
      ]
    }
  ],
  "PaleFlame": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Freminet_PHYSICAL DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Xinyan_PHYSICAL DPS"
      ]
    }
  ],
  "ThunderingFury": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Beidou_OFF-FIELD DPS",
        "Keqing_AGGRAVATE DPS",
        "Keqing_QUICKBLOOM DPS",
        "Lisa_AGGRAVATE DPS",
        "Raiden_DPS & ENERGY SUPPORT"
      ]
    }
  ],
  "Thundersoother": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Keqing_AGGRAVATE DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ningguang_DPS"
      ]
    }
  ],
  "ArchaicPetra": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Ningguang_DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Kachina_BUFF & REACTION SUPPORT",
        "Noelle_DRIVER",
        "Xilonen_BUFF & HEAL SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Zhongli_SHIELD SUPPORT"
      ]
    }
  ],
  "Lavawalker": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "enerRech_"
      ],
      "source_characters": [
        "Lyney_DPS",
        "Ningguang_DPS"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Xinyan_PYRO DPS"
      ]
    }
  ],
  "HuskOfOpulentDreams": [
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Noelle_DPS",
        "Yunjin_BUFF SUPPORT"
      ]
    },
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Chiori_OFF-FIELD DPS"
      ]
    }
  ],
  "RetracingBolide": [
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Noelle_DPS"
      ]
    }
  ],
  "TheExile": [
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Gorou_BUFF SUPPORT"
      ]
    }
  ],
  "HeartOfDepth": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Mona_BURST NUKE(OUT OF DATE)",
        "Mona_DPS(OUT OF DATE)",
        "Tartaglia_DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Yelan_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Yelan_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Mualani_VAPORIZE DPS"
      ]
    }
  ],
  "NymphsDream": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Mona_BURST NUKE(OUT OF DATE)",
        "Tartaglia_DPS"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Yelan_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Yelan_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    }
  ],
  "VourukashasGlow": [
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "enerRech_",
        "hp_"
      ],
      "source_characters": [
        "Yelan_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
        "Yelan_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
      ]
    },
    {
      "substats_desired": [
        "critDMG_",
        "critRate_",
        "eleMas",
        "hp_"
      ],
      "source_characters": [
        "Nilou_BLOOM SUPPORT"
      ]
    }
  ],
  "CrimsonWitchOfFlames": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "eleMas",
        "enerRech_"
      ],
      "source_characters": [
        "Bennett_DPS",
        "Diluc_DPS",
        "Gaming_DPS",
        "Xiangling_OFF-FIELD DPS",
        "Xiangling_OFF-FIELD VAPORIZE DPS",
        "Yanfei_VAPORIZE DPS"
      ]
    }
  ],
  "BloodstainedChivalry": [
    {
      "substats_desired": [
        "atk_",
        "critDMG_",
        "critRate_",
        "def_",
        "enerRech_"
      ],
      "source_characters": [
        "Xinyan_PHYSICAL DPS"
      ]
    }
  ]
};

// A raw list of general-purpose builds for Sands, Goblets, and Circlets.
// Each entry defines a valid combination of main stats and desired substats.
const GSC_RAW_BUILDS = [
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Sucrose_EM SUPPORT"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_",
      "eleMas"
    ],
    "circlet_main": [
      "eleMas",
      "heal_"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Sayu_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "anemo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Heizou_ANEMO DPS",
      "Ifa_ANEMO DPS",
      "Venti_ON-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Heizou_REACTION DPS"
    ]
  },
  {
    "sands_main": [
      "enerRech_"
    ],
    "goblet_main": [
      "anemo_dmg_",
      "critRate_",
      "enerRech_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Faruzan_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "anemo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Lynette_OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_"
    ],
    "circlet_main": [
      "atk_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Lanyan_SHIELD & BUFFSUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_",
      "eleMas"
    ],
    "circlet_main": [
      "atk_",
      "critRate_",
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Lanyan_DRIVER"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Ifa_REACTION DPS",
      "Lisa_REACTION DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_"
    ],
    "circlet_main": [
      "atk_",
      "critRate_",
      "heal_"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Jahoda_OFF-FIELD REACTION DPS & HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "anemo_dmg_",
      "eleMas"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "MC (Anemo)_ANEMO DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "heal_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Jean_HEAL SUPPORT & DAMAGE"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Jean_REACTION DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "anemo_dmg_",
      "atk_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Venti_OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Lauma_BUFF SUPPORT (HIGH-ENERGY REQUIREMENT)",
      "Mizuki_REACTION DPS"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "heal_",
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Diona_HEAL & SHIELD SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Chongyun_BURST NUKE",
      "Kaeya_REVERSE MELT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Chongyun_INFUSION SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Ganyu_FREEZE DPS",
      "Kaeya_FREEZE / MONO CRYO",
      "Rosaria_FREEZE"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Aloy_BURST SUPPORT",
      "Rosaria_REVERSEMELT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Rosaria_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "critRate_",
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Kirara_SHIELD SUPPORT",
      "Layla_SHIELD SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "cryo_dmg_",
      "hp_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "hp_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Layla_SHIELD SUPPORT AND DAMAGE"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "critRate_",
      "heal_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Mika_HEAL & BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "physical_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Freminet_PHYSICAL DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Freminet_CRYO DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_"
    ],
    "circlet_main": [
      "atk_",
      "critRate_",
      "heal_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Charlotte_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_"
    ],
    "circlet_main": [
      "atk_",
      "heal_"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Qiqi_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas"
    ],
    "source_characters": [
      "Ganyu_MELT DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Ganyu_MONO CRYO DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "cryo_dmg_"
    ],
    "circlet_main": [
      "atk_",
      "critDMG_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Ayaka_DPS"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "critRate_",
      "eleMas"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Aino_REACTION SUPPORT",
      "Citlali_BUFF SUPPORT",
      "Kaveh_BLOOM / BURGEON DRIVER"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_",
      "atk_",
      "cryo_dmg_",
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Escoffier_HIGH ENERGY REQUIREMENT (OFF-FIELD DPS)"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "atk_",
      "atk_",
      "cryo_dmg_",
      "cryo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Escoffier_LOW ENERGY REQUIREMENT (OFF-FIELD DPS)"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "dendro_dmg_",
      "eleMas"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Collei_REACTION SUPPORT",
      "MC (Dendro)_REACTION SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "heal_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Yaoyao_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "dendro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Tighnari_QUICK SWAP DPS"
    ]
  },
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "dendro_dmg_",
      "eleMas"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Nahida_BUFF SUPPORT & DAMAGE"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "dendro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Emilie_OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "critRate_",
      "eleMas"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Lauma_BUFF SUPPORT(LOW-ENERGY REQUIREMENT)"
    ]
  },
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Nefer_DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Fischl_OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Clorinde_DPS",
      "Fischl_OFF-FIELD AGGRAVATE DPS",
      "Keqing_AGGRAVATE DPS",
      "Keqing_QUICKBLOOM DPS",
      "Lisa_AGGRAVATE DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Beidou_OFF-FIELD AGGRAVATE DPS",
      "Beidou_OFF-FIELD DPS",
      "Yaemiko_OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Lisa_OFF-FIELD DPS & SUPPORT",
      "Yaemiko_OFF-FIELD AGGRAVATE DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Razor_DPS"
    ]
  },
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Barbara_BLOOM DPS",
      "Raiden_HYPERBLOOM",
      "Razor_HYPERBLOOM / REACTION DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Sara_BUFF SUPPORT & DAMAGE"
    ]
  },
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Kokomi_BLOOM DPS",
      "Kuki_HYPERBLOOM"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Kuki_AGGRAVATE OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "critRate_",
      "heal_",
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "hp_"
    ],
    "source_characters": [
      "Kuki_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "eleMas",
      "hp_"
    ],
    "circlet_main": [
      "critRate_",
      "eleMas",
      "heal_",
      "hp_"
    ],
    "substats_desired": [
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Dori_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Sethos_CHARGED ATTACK DPS",
      "Sethos_NORMAL ATTACK DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_",
      "enerRech_"
    ],
    "goblet_main": [
      "eleMas",
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "eleMas"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Ororon_OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_"
    ],
    "circlet_main": [
      "atk_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Iansan_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_"
    ],
    "goblet_main": [
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "MC (Electro)_ENERGY SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_",
      "electro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Raiden_DPS & ENERGY SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "geo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "MC (Geo)_GEO DPS",
      "Navia_DPS",
      "Ningguang_DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "atk_",
      "def_"
    ],
    "goblet_main": [
      "geo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Noelle_DPS"
    ]
  },
  {
    "sands_main": [
      "def_"
    ],
    "goblet_main": [
      "def_",
      "geo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "def_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Noelle_DRIVER"
    ]
  },
  {
    "sands_main": [
      "enerRech_"
    ],
    "goblet_main": [
      "def_",
      "geo_dmg_"
    ],
    "circlet_main": [
      "critRate_",
      "def_",
      "heal_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Gorou_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "def_",
      "enerRech_"
    ],
    "goblet_main": [
      "def_"
    ],
    "circlet_main": [
      "critRate_",
      "def_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Yunjin_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "def_",
      "enerRech_"
    ],
    "goblet_main": [
      "def_",
      "geo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Kachina_BUFF & REACTION SUPPORT"
    ]
  },
  {
    "sands_main": [
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "critRate_",
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Dehya_SUPPORT",
      "Zhongli_SHIELD SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "hp_"
    ],
    "goblet_main": [
      "geo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Zhongli_BURST SUPPORT"
    ]
  },
  {
    "sands_main": [
      "def_"
    ],
    "goblet_main": [
      "geo_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Chiori_OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "def_",
      "enerRech_"
    ],
    "goblet_main": [
      "def_"
    ],
    "circlet_main": [
      "critRate_",
      "def_",
      "heal_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Xilonen_BUFF & HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Xingqiu_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
      "Xingqiu_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
    ]
  },
  {
    "sands_main": [
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "heal_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Barbara_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_",
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Candace_BUFF SUPPORT",
      "Yelan_HIGH ENERGY REQUIREMENT(OFF-FIELD DPS)",
      "Yelan_LOW ENERGY REQUIREMENT(OFF-FIELD DPS)"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Dahlia_SHIELD SUPPORT",
      "Yanfei_SHIELD SUPPORT [C4+ REQUIRED]"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "heal_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "MC (Hydro)_SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "MC (Hydro)_ON-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Mona_DPS(OUT OF DATE)",
      "Tartaglia_DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Mona_BURST NUKE(OUT OF DATE)"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "atk_",
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Mona_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "heal_",
      "hp_"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Kokomi_HEAL SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hydro_dmg_"
    ],
    "circlet_main": [
      "heal_"
    ],
    "substats_desired": [
      "atk_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Kokomi_DPS"
    ]
  },
  {
    "sands_main": [
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "hp_"
    ],
    "source_characters": [
      "Nilou_BLOOM SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_",
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Furina_OFF-FIELD DPS & BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "hp_"
    ],
    "goblet_main": [
      "hydro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "hp_"
    ],
    "source_characters": [
      "Mualani_VAPORIZE DPS"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Columbina_OFF-FIELD DPS & BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas"
    ],
    "source_characters": [
      "Amber_MELT DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Amber_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Gaming_DPS",
      "MC (Pyro)_DPS",
      "Xiangling_OFF-FIELD DPS",
      "Xiangling_OFF-FIELD VAPORIZE DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_",
      "pyro_dmg_"
    ],
    "circlet_main": [
      "heal_",
      "hp_"
    ],
    "substats_desired": [
      "atk_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Bennett_SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Bennett_DPS",
      "Diluc_DPS",
      "Yanfei_VAPORIZE DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "physical_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Xinyan_PHYSICAL DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Xinyan_PYRO DPS"
    ]
  },
  {
    "sands_main": [
      "def_",
      "enerRech_"
    ],
    "goblet_main": [
      "def_"
    ],
    "circlet_main": [
      "def_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "Xinyan_SHIELD SUPPORT"
    ]
  },
  {
    "sands_main": [
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Thoma_BURGEON"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "critRate_",
      "critRate_",
      "hp_"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Thoma_SHIELD SUPPORT"
    ]
  },
  {
    "sands_main": [
      "enerRech_",
      "hp_"
    ],
    "goblet_main": [
      "hp_"
    ],
    "circlet_main": [
      "heal_",
      "hp_"
    ],
    "substats_desired": [
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Chevreuse_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Chevreuse_BUFF SUPPORT & DAMAGE"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "enerRech_"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "def_",
      "enerRech_"
    ],
    "source_characters": [
      "MC (Pyro)_BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas",
      "enerRech_"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_",
      "hp_"
    ],
    "source_characters": [
      "Dehya_ON FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "eleMas"
    ],
    "goblet_main": [
      "eleMas"
    ],
    "circlet_main": [
      "eleMas"
    ],
    "substats_desired": [
      "critDMG_",
      "critRate_",
      "eleMas",
      "hp_"
    ],
    "source_characters": [
      "Dehya_REACTION DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Lyney_DPS"
    ]
  },
  {
    "sands_main": [
      "atk_",
      "eleMas"
    ],
    "goblet_main": [
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas"
    ],
    "source_characters": [
      "Arlecchino_DPS",
      "Mavuika_DPS & BUFF SUPPORT"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "atk_",
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "eleMas",
      "enerRech_"
    ],
    "source_characters": [
      "Durin_VAPORIZE / MELT OFF-FIELD DPS"
    ]
  },
  {
    "sands_main": [
      "atk_"
    ],
    "goblet_main": [
      "atk_",
      "pyro_dmg_"
    ],
    "circlet_main": [
      "critDMG_",
      "critRate_"
    ],
    "substats_desired": [
      "atk_",
      "critDMG_",
      "critRate_",
      "enerRech_"
    ],
    "source_characters": [
      "Durin_BUFF SUPPORT & OFF-FIELD DPS"
    ]
  }
];

// --- PERFORMANCE INDEXING (RUNTIME OPTIMIZATION) ---
// This runs once when the script is loaded.
// It converts the linear GSC_RAW_BUILDS list into a hash map for O(1) lookups.

const OPTIMIZED_GSC_INDEX = {
  sands: {},
  goblet: {},
  circlet: {}
};

// Helper to populate the index
function addToIndex(slot, mainStats, desiredSubs) {
  if (!mainStats) return;
  // Convert desired subs to a Set for O(1) lookup speed during scanning
  const desiredSet = new Set(desiredSubs);
  
  mainStats.forEach(mainStat => {
    if (!OPTIMIZED_GSC_INDEX[slot][mainStat]) {
      OPTIMIZED_GSC_INDEX[slot][mainStat] = [];
    }
    OPTIMIZED_GSC_INDEX[slot][mainStat].push(desiredSet);
  });
}

// Build the Index immediately
if (Array.isArray(GSC_RAW_BUILDS)) {
  GSC_RAW_BUILDS.forEach(build => {
    addToIndex('sands', build.sands_main, build.substats_desired);
    addToIndex('goblet', build.goblet_main, build.substats_desired);
    addToIndex('circlet', build.circlet_main, build.substats_desired);
  });
}

// --- MAIN LOGIC ---

/**
 * Main function to determine if an artifact should be locked.
 * @param {Artifact} artifact - The artifact to evaluate.
 * @returns {boolean | null} - True to lock, false to unlock, null to ignore.
 */
module.exports = (artifact) => {
  
  // Rule 0: Ignore anything that isn't a 5-star artifact.
  if (artifact.rarity < 5) return false;

  const artifactSubstats = artifact.substats.map(s => s.key);

  // Rule 1: Universal lock for any piece with both Crit Rate and Crit Damage.
  // This is a safety net for high-potential pieces regardless of set.
  let hasCR = false;
  let hasCD = false;
  for (const key of artifactSubstats) {
    if (key === 'critRate_') hasCR = true;
    if (key === 'critDMG_') hasCD = true;
  }
  if (hasCR && hasCD) return true;

  // Determine the minimum number of desired substats required based on starting lines.
  const threshold = artifact.substats.length === 4
    ? CONFIG.DESIRED_SUBSTAT_COUNT_4_LINE
    : CONFIG.DESIRED_SUBSTAT_COUNT_3_LINE;

  const { slotKey, setKey, mainStatKey } = artifact;

  // Rule 2a: Logic for Flowers and Plumes (Strict Set Matching).
  if (slotKey === 'flower' || slotKey === 'plume') {
    const buildsForSet = FLOWER_PLUME_BUILDS[setKey];
    if (!buildsForSet) return false; // This set is not in our desired list for F/P.

    // Check if the artifact's substats match any of the defined builds for this set.
    for (const build of buildsForSet) {
      let matchCount = 0;
      for (const sub of artifactSubstats) {
        if (build.substats_desired.includes(sub)) matchCount++;
      }
      if (matchCount >= threshold) return true;
    }
    return false;
  }
  
  // Rule 2b: Logic for Sands, Goblets, and Circlets (Indexed Lookup).
  // We check the optimized index to see if ANY build needs this Main Stat + Slot combo.
  
  const validBuilds = OPTIMIZED_GSC_INDEX[slotKey]?.[mainStatKey];
  
  // If NO character in the database uses this Main Stat on this Slot, trash it.
  if (!validBuilds) return false;

  // Check against the specific builds that use this Main Stat
  for (const desiredSet of validBuilds) {
    let matchCount = 0;
    for (const sub of artifactSubstats) {
      // Set.has() is instant (O(1)) compared to Array.includes()
      if (desiredSet.has(sub)) matchCount++;
    }
    if (matchCount >= threshold) return true;
  }

  // If no rules were met, do not lock the artifact.
  return false;
};
